name: api server build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build-api-server-aarch64v8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82"
          override: true
          default: true
          components: rustfmt
          profile: minimal
          target: aarch64-unknown-linux-gnu

      - name: Build
        uses: ClementTsang/cargo-action@v0.0.3
        with:
          command: build
          args: --release --all-features --target=aarch64-unknown-linux-gnu
          directory: api_server
          use-cross: true

      - name: Package and export
        run: |
          cd api_server
          mkdir -p release
          cp target/aarch64-unknown-linux-gnu/release/api_server release/ 2>/dev/null || :
          tar czvf api-server-release.tar.gz -C release .
          echo "PACKAGE_PATH=$(pwd)/api-server-release.tar.gz" >> $GITHUB_ENV

      - name: Upload release package
        uses: actions/upload-artifact@v4
        with:
          name: api-server-release-aarch64v8
          path: ${{ env.PACKAGE_PATH }}
          if-no-files-found: error
