name: mtls server build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-mtls-server-aarch64v8:
    runs-on: ubuntu-latest

    outputs:
      release_ready: ${{ steps.tag_check.outputs.is_release }}

    steps:
    - uses: actions/checkout@v4

    - name: Install ARM cross-compilation toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Install VCPKG and dependencies
      id: vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg install uthash kcp wolfssl --triplet arm64-linux
        VCPKG_PATH=$(pwd)
        TOOLCHAIN_PATH=$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake
        echo "VCPKG_CMAKE_TOOLCHAIN=$TOOLCHAIN_PATH" >> $GITHUB_ENV
        echo "VCPKG_PATH=$VCPKG_PATH" >> $GITHUB_ENV
        find $VCPKG_PATH/installed/arm64-linux -name "*wolfssl*.cmake"

    - name: Configure with CMake
      run: |
        echo "current pwd: $(pwd)"
        cd mtls_server
        cmake -S ./ -B ./build \
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_CMAKE_TOOLCHAIN }} \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=arm64 \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -Dwolfssl_DIR=${{ env.VCPKG_PATH }}/installed/arm64-linux/share/wolfssl

    - name: Build
      run: |
        cd mtls_server
        cmake --build ./build --config Release

    - name: Package and export
      run: |
        cd mtls_server
        mkdir -p release/
        cp build/mtls_server release/ 2>/dev/null || :
        cp -r assets/ release/ 2>/dev/null || :
        tar czvf mtls-server-release.tar.gz -C release .
        echo "PACKAGE_PATH=$(pwd)/mtls-server-release.tar.gz" >> $GITHUB_ENV

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: mtls-server-release-aarch64v8
        path: ${{ env.PACKAGE_PATH }}
